name: RC
on:
  push:
    branches: [master, ci-build-rc]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    if: >
      !contains(github.event.head_commit.message, '#skip-ci')
    runs-on: mbw-builder
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: docker/build-push-action@v4
      with:
        tags: mycelium_builder:latest
        push: false
        context: ${{ github.workspace }}

    - uses: addnab/docker-run-action@v3
      with:
        image: mycelium_builder:latest
        options: >
          --volume ${{ github.workspace }}:/app/
          --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
        run: |
          mkdir /project/
          disorderfs --sort-dirents=yes --reverse-dirents=no /app/ /project/;
          cd /project/
          ./gradlew --no-daemon --parallel --configure-on-demand clean test mbw:assembleProdnetDebug mbw:assembleBtctestnetDebug mbw:assembleProdnetRelease mbw:assembleBtctestnetRelease mbw:assembleHuaweiProdnetRelease 

    - uses: actions/upload-artifact@v4
      with:
        path: |
          mbw/build/outputs/
          mbw/build/outputs/native-debug-symbols/
